#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : abydos
Version  : 0.5.0
Release  : 3
URL      : https://files.pythonhosted.org/packages/30/53/4d8dfccbbfe6031a2293941d718dfda7cf2e39883f915b5e3b2c057b518c/abydos-0.5.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/30/53/4d8dfccbbfe6031a2293941d718dfda7cf2e39883f915b5e3b2c057b518c/abydos-0.5.0.tar.gz
Summary  : Abydos NLP/IR library
Group    : Development/Tools
License  : GPL-3.0 GPL-3.0+
Requires: abydos-license = %{version}-%{release}
Requires: abydos-python = %{version}-%{release}
Requires: abydos-python3 = %{version}-%{release}
Requires: deprecation
Requires: numpy
BuildRequires : buildreq-distutils3
BuildRequires : deprecation
BuildRequires : numpy

%description
======
        
        +------------------+------------------------------------------------------+
        | CI & Test Status | |travis| |circle| |azure| |semaphore| |coveralls|    |
        +------------------+------------------------------------------------------+
        | Code Quality     | |codeclimate| |scrutinizer| |codacy| |codefactor|    |
        +------------------+------------------------------------------------------+
        | Dependencies     | |requires| |snyk| |pyup| |cii|                       |
        +------------------+------------------------------------------------------+
        | Local Analysis   | |pylint| |flake8| |pydocstyle| |sloccount| |black|   |
        +------------------+------------------------------------------------------+
        | Usage            | |docs| |mybinder| |license| |sourcerank| |zenodo|    |
        +------------------+------------------------------------------------------+
        | Contribution     | |openhub| |gh-commits| |gh-issues| |gh-stars|        |
        +------------------+------------------------------------------------------+
        | PyPI             | |pypi| |pypi-dl| |pypi-ver|                          |
        +------------------+------------------------------------------------------+
        | conda-forge      | |conda| |conda-dl| |conda-platforms|                 |
        +------------------+------------------------------------------------------+

%package license
Summary: license components for the abydos package.
Group: Default

%description license
license components for the abydos package.


%package python
Summary: python components for the abydos package.
Group: Default
Requires: abydos-python3 = %{version}-%{release}

%description python
python components for the abydos package.


%package python3
Summary: python3 components for the abydos package.
Group: Default
Requires: python3-core
Provides: pypi(abydos)
Requires: pypi(deprecation)
Requires: pypi(numpy)

%description python3
python3 components for the abydos package.


%prep
%setup -q -n abydos-0.5.0
cd %{_builddir}/abydos-0.5.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1635701373
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/abydos
cp %{_builddir}/abydos-0.5.0/LICENSE %{buildroot}/usr/share/package-licenses/abydos/df07b60f0574125f0136eaa0f2dbdc382bfc647b
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/abydos/df07b60f0574125f0136eaa0f2dbdc382bfc647b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
